# Generated by Django 4.2.4 on 2025-10-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=500, verbose_name="Author to'liq ismi")),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Author ni rasmi')),
            ],
            options={
                'verbose_name': 'Muallif',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='Kitobni nomi')),
                ('description', models.TextField(verbose_name='Kitob haqida ')),
                ('image', models.ImageField(blank=True, upload_to='book/', verbose_name='Kitobni rasmi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author', verbose_name='Kitobning Muallifi')),
            ],
            options={
                'verbose_name': 'Kitoblar_',
            },
        ),
    ]
